<!doctype html>
<html>
<head>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"/>
</head>
<body>
<div class="container">
	<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
		<a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
			${logo}
		</a>
		<span class="fs-4">${title}</span>
	</header>
	<div class="row">
		<div class="col-3">
			${menu}
		</div>
		<div class="col-9">
			${content}
		</div>
	</div>
</div>
</body>
</html>
